# Generated by Django 2.0.6 on 2018-07-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180727_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/<django.db.models.fields.CharField>'),
        ),
    ]
