# Generated by Django 2.0.6 on 2018-07-27 12:59

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180727_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.profile_pic_path),
        ),
    ]
