# Generated by Django 2.0.6 on 2018-08-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180727_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='representatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repname', models.CharField(max_length=20)),
            ],
        ),
    ]
