# Generated by Django 2.0.6 on 2018-08-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_representatives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='representatives',
        ),
    ]
