# Generated by Django 2.0.6 on 2018-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_minuteofmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuteofmeeting',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
