# Generated by Django 2.0.6 on 2018-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180811_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='Documents')),
            ],
        ),
    ]
