# Generated by Django 2.0.6 on 2018-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_reports_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calender', models.CharField(max_length=50)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='Documents')),
            ],
        ),
    ]
