# Generated by Django 2.0.6 on 2018-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='Calender'),
        ),
    ]
