# Generated by Django 2.0.6 on 2018-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180820_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repname', models.CharField(max_length=20)),
            ],
        ),
    ]
