# Generated by Django 2.0.6 on 2018-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_representatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='repemail',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='representatives',
            name='repimage',
            field=models.FileField(blank=True, null=True, upload_to='rep_img'),
        ),
        migrations.AlterField(
            model_name='representatives',
            name='repname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
