# Generated by Django 2.0.6 on 2018-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20180820_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='reppost',
            field=models.CharField(default='', max_length=30),
        ),
    ]
