# Generated by Django 2.0.6 on 2018-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180823_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='postdate',
            field=models.DateTimeField(default='datetime.datetime.now()'),
        ),
    ]
