# Generated by Django 2.0.6 on 2018-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20180823_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
