# Generated by Django 2.0.6 on 2018-08-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20180823_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('rollno', models.IntegerField(default='', max_length=10)),
                ('mobno', models.IntegerField(default='', max_length=10)),
                ('problem', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
    ]
