# Generated by Django 2.0.6 on 2018-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20180829_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='department',
            field=models.CharField(choices=[('IN', 'Infrastructure'), ('HM', 'Hostels Maintainence'), ('MF', 'Mess Food'), ('AC', 'Academics'), ('SP', 'Sports'), ('SA', 'Students Activities'), ('OT', 'Others')], default='', max_length=2),
        ),
    ]
