# Generated by Django 2.0.6 on 2018-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='repcat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
