# Generated by Django 2.0.6 on 2018-08-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_representatives_repcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='repcat',
            field=models.CharField(choices=[('CM', 'Core Member'), ('TE', 'Team Engi'), ('TI', 'Team Inci'), ('SE', 'Secreatory'), ('CR', 'Class Representatives')], default='', max_length=20),
        ),
    ]
