# Generated by Django 2.0.6 on 2018-08-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20180830_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='repcat',
            field=models.CharField(choices=[('CM', 'Core Member'), ('TE', 'Team Engi'), ('TI', 'Team Inci'), ('SE', 'Technical Secreatories'), ('CA', 'Cultural and Alumni Secreatories'), ('FR', 'First Year Class Representatives'), ('SR', 'Second Year Class Representatives'), ('TR', 'Third Year Class Representatives'), ('RF', 'Fourth Year Class Representatives'), ('PG', 'PG Class Representatives')], default='', max_length=2),
        ),
    ]
