# Generated by Django 2.0.6 on 2018-09-01 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20180830_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='eventdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
