# Generated by Django 2.0.6 on 2018-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_councilmess'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
