# Generated by Django 2.0.6 on 2018-10-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='rep_img'),
        ),
    ]
