# Generated by Django 2.0.6 on 2018-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_developers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='dev_img'),
        ),
        migrations.AlterField(
            model_name='developers',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
