# Generated by Django 2.0.6 on 2018-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20181026_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='rep_course',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='representatives',
            name='rep_department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='representatives',
            name='rep_mob_mo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='representatives',
            name='rep_roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='representatives',
            name='rep_yearsofstudy',
            field=models.CharField(default='', max_length=10),
        ),
    ]
