# Generated by Django 2.0.6 on 2018-11-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20181105_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='rep_roll_no',
            field=models.CharField(default='', max_length=8),
        ),
    ]
