# Generated by Django 2.0.6 on 2018-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20181105_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='rep_degree',
            field=models.CharField(default='', max_length=2),
        ),
    ]
