# Generated by Django 2.0.6 on 2018-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_representatives_rep_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='rep_department',
            field=models.CharField(default='', max_length=40),
        ),
    ]
