# Generated by Django 2.0.6 on 2018-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20181105_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='repemail',
            field=models.EmailField(default='', max_length=40),
        ),
    ]
